name: First Workflow

# WHEN TO RUN
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  first-job:
    # RUNNERS: https://docs.github.com/es/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Print greeting
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Print goodbye
        run: |
          echo Nothing to do here,
          echo Bye!
